# Generated by Django 3.1.7 on 2021-07-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('raca', models.CharField(max_length=15)),
                ('codColeira', models.CharField(max_length=40)),
            ],
        ),
    ]
