# Generated by Django 3.1.7 on 2021-07-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='dataNascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('p', 'pequeno'), ('m', 'médio'), ('g', 'grande')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('m', 'macho'), ('f', 'fêmea')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(max_length=20),
        ),
    ]
