# Generated by Django 3.1.7 on 2021-08-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
    ]
