# Generated by Django 3.1.7 on 2021-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_pet_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
