# Generated by Django 3.1.7 on 2022-02-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='user',
            new_name='pet',
        ),
    ]
