# Generated by Django 3.1.7 on 2022-02-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20220201_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='Nome',
            new_name='nome',
        ),
    ]
