# Generated by Django 3.1.7 on 2022-02-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_auto_20220201_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='porte',
            new_name='tipo',
        ),
    ]
