# Generated by Django 3.1.7 on 2022-02-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_auto_20220201_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tipo',
            field=models.CharField(choices=[('v', 'vacina'), ('p', 'procedimento cirurgico'), ('c', 'cuidados')], max_length=1, null=True),
        ),
    ]
