# Generated by Django 3.1.7 on 2021-04-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('tel', models.BigIntegerField(verbose_name='tel')),
                ('password', models.CharField(max_length=10, verbose_name='password')),
            ],
        ),
    ]
